### PR TITLE
8.x

### PR DESCRIPTION
**Pull request by pusle**
I have ported the 7.x module to 8.x "as is", with blocks being used to show the tracking pixel and form js. I haven't written tests, as I do not know how to, but it is tested manually. 

Right now I am working on a version that uses the tracking script instead of the pixel and will be updating my code some time this week. 

Is this merge-material as it is now?

### CODE REVIEW

**Comment by escopecz** [comment]
I haven't develop a plugin for D8 yet, so I can't tell much, but thank you, this looks good!

**Comment by pusle** [comment]
I have removed the tracking pixel and the module is now using the tracking script. Just let me know if there is something I can do/fix so you can accept the pull request if you are interested.

**Comment by pietervanleuven** [comment]
Hi, I have checked out both 8.x pull requests and this one has my preference. It uses the javascript tracking code instead of the tracking pixel, which is good.

**Comment by rinasek** [comment]
I have tested this pull request a couple of times in last two days and it simply does not work.

- Module is enabled and configured (forms embed is enabled too)
- I get tracking script in HTML <script async="" src="http://example.com/mtc.js"></script>
- Block is in footer (not sure if this is the neceasry step but behavior is always same either way).
- Shortcode is in content but form just does not show up. There are no errors in the console and nothing happens.

**Comment by pusle** [comment]
@rinasek ~~Sorry, still have only implemented the tracking pixel.~~  Actually, I can not remember, it has been so long. I will take a look at this tomorrow, as perhaps changes to Drupal 8 (a lot has changed since I did this) may be screwing things up.

**Comment by rinasek** [comment]
@pusle It could be. I have seen that there is Mautic Form block in the block list.

**Comment by pusle** [comment]
@rinasek Sorry to say that I will not get the time to look at this now, it will have to wait until the weekend as something has come up.

**Comment by rinasek** [comment]
@pusle Anything new? Have you had time to check things?

**Comment by pusle** [comment]
@rinasek Yes, I have checked it out, but only yesterday. For my version on Drupal and Mautic, the forms work fine, both automatic (javascript) and manual copy of form to a block in Drupal. I do get a 500 error when submitting the form though, so I am checking that out now.

(Mautic 2.9.2 and Drupal 8.2.6)

**Comment by rinasek** [comment]
@pusle I am going to check it again at the beginning of next week to see what is happening.

**Pull request closed without merging**
